/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package colibri;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonElement;
import colibri.Collector;

public class App {
    String getGreeting() {
        String myString = "{'a':'1','b':'2'}";
        JsonParser jp = new JsonParser();
        JsonElement je = jp.parse(myString);
        if (je.isJsonObject()) {
            JsonObject o = je.getAsJsonObject();
            System.out.println(o.get("a").getAsInt());
            System.out.println(o.get("b").getAsInt());
            return o.toString();
        } else {
            return "Not Object";
        }
    }

    public interface Market {
        String name;
        String[] tradePairs;
    }

    Market[] getMarkets(String settings) {

    }


    public static void main(String[] args) {
        String settings = "";
        Market[] markets = getMarkets(settings);
        for (Market market : markets) {
            for (String tp : market.tradePairs)
                Collector t = new Collector();
        }
    }
}
